name: kafeteria_alkhair
description: تطبيق كافتيريا الخير - العصائر الطازجة والوجبات الخفيفة
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
flutter:
  fonts:
    - family: GoogleFonts
      fonts:
        - asset: https://fonts.googleapis.com/css2?family=Cairo:wght@400;700&display=swap
  flutter:
    sdk: flutter
  provider: ^6.0.5
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  image_picker: ^0.8.9
  http: ^0.13.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/products/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
